"""add slug and is_solved columns

Revision ID: 128d27fbf8d5
Revises: a66f1c59af45
Create Date: 2025-12-19 15:49:35.558503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '128d27fbf8d5'
down_revision: Union[str, Sequence[str], None] = 'a66f1c59af45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problem_problem_no'), table_name='problem')
    op.drop_index(op.f('ix_problem_title'), table_name='problem')
    op.drop_table('problem')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem',
    sa.Column('problem_no', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('difficulty', sa.VARCHAR(length=9), nullable=False),
    sa.Column('solution_cpp', sa.VARCHAR(), nullable=True),
    sa.Column('is_solved', sa.BOOLEAN(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_title'), 'problem', ['title'], unique=False)
    op.create_index(op.f('ix_problem_problem_no'), 'problem', ['problem_no'], unique=1)
    # ### end Alembic commands ###
