"""initial_schema

Revision ID: 1f18fe37ea31
Revises: 
Create Date: 2025-12-20 14:23:35.697100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f18fe37ea31'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem',
    sa.Column('problem_no', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'DIFFICULT', name='difficulty'), nullable=False),
    sa.Column('solution_cpp', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_solved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_problem_problem_no'), ['problem_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_problem_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_problem_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_problem_title'))
        batch_op.drop_index(batch_op.f('ix_problem_slug'))
        batch_op.drop_index(batch_op.f('ix_problem_problem_no'))

    op.drop_table('problem')
    # ### end Alembic commands ###
